name: mobile_trampoline_park
description: "Trampoline park 1"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  intl_utils: ^2.8.10
  flutter_svg: ^2.0.17
  auto_route: ^10.0.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  video_player: ^2.9.5
  yandex_mapkit: ^4.1.0
  url_launcher: ^6.3.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  flutter_lints: ^5.0.0
  build_runner: 
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/on_boarding_pictures/
  fonts:
    - family: SofiaSans
      fonts:
        - asset: assets/fonts/SofiaSans-Black.ttf
          weight: 900
        - asset: assets/fonts/SofiaSans-Medium.ttf
          weight: 500
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

          
flutter_intl:
  enabled: true
  arb_dir: lib/presentation/resources/localizations/l10n
  output_dir: lib/presentation/resources/localizations/generated
