# Generated by Django 5.1.4 on 2025-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trampoline_park', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='optional_service',
            field=models.ManyToManyField(blank=True, null=True, to='trampoline_park.optionalservice', verbose_name='Дополнительные услуги'),
        ),
    ]
