# Generated by Django 5.1.4 on 2025-03-14 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trampoline_park', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterModelOptions(
            name='coachachievement',
            options={'verbose_name': 'Достижение тренера', 'verbose_name_plural': 'Достижения тренера'},
        ),
        migrations.AlterModelOptions(
            name='coachcostume',
            options={'verbose_name': 'Костюм тренера', 'verbose_name_plural': 'Костюмы тренера'},
        ),
        migrations.AlterModelOptions(
            name='coachspecialty',
            options={'verbose_name': 'Специальность тренера', 'verbose_name_plural': 'Специальности тренера'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='optionalservice',
            options={'verbose_name': 'Дополнительная услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='photovideoserviceprice',
            options={'verbose_name': 'Цена фото/видео услуг', 'verbose_name_plural': 'Цены фото/видео услуг'},
        ),
        migrations.AlterModelOptions(
            name='typeoptionalservice',
            options={'verbose_name': 'Тип дополнительной услуги', 'verbose_name_plural': 'Типы дополнительных услуг'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'verbose_name': 'Тип тренировки', 'verbose_name_plural': 'Типы тренировок'},
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_healthy',
            field=models.BooleanField(verbose_name='Сведения о здорвье'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='achievements',
            field=models.ManyToManyField(to='trampoline_park.coachachievement', verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='profile_picture',
            field=models.FileField(upload_to='profile_pictures', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='quote',
            field=models.TextField(max_length=300, null=True, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='specialties',
            field=models.ManyToManyField(to='trampoline_park.coachspecialty', verbose_name='Специальности'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='coachachievement',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='coachcostume',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coachcostume',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='coachspecialty',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='event',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trampoline_park.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trampoline_park.coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coach_costume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trampoline_park.coachcostume', verbose_name='Костюм'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_photographer',
            field=models.BooleanField(verbose_name='Услуги фотографа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_videographer',
            field=models.BooleanField(verbose_name='Услуги видеографа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='optional_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trampoline_park.optionalservice', verbose_name='Дополнительные услуги'),
        ),
        migrations.AlterField(
            model_name='optionalservice',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='optionalservice',
            name='optional_service_picture',
            field=models.FileField(upload_to='optional_service_pictures', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='optionalservice',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='optionalservice',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trampoline_park.typeoptionalservice', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='photovideoserviceprice',
            name='photographer_price',
            field=models.IntegerField(verbose_name='Цена фотографа'),
        ),
        migrations.AlterField(
            model_name='photovideoserviceprice',
            name='videographer_price',
            field=models.IntegerField(verbose_name='Цена видеографа'),
        ),
        migrations.AlterField(
            model_name='typeoptionalservice',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Тип дополнительной услуги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'CLIENT'), ('COACH', 'COACH'), ('ADMIN', 'ADMIN')], default='ADMIN', max_length=50, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='clients',
            field=models.ManyToManyField(blank=True, to='trampoline_park.client', verbose_name='Клиент(ы)'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trampoline_park.coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trampoline_park.workouttype', verbose_name='Тип тренировки'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание тренировки'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='max_clients',
            field=models.IntegerField(default=1, verbose_name='Максимальное количество клиентов'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название тренировки'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='workout_picture',
            field=models.FileField(upload_to='workout_pictures', verbose_name='Фото'),
        ),
    ]
