# Generated by Django 5.1.4 on 2025-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trampoline_park', '0002_alter_event_optional_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachcostume',
            name='name',
            field=models.CharField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='optionalservice',
            name='name',
            field=models.CharField(unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='typeoptionalservice',
            name='name',
            field=models.CharField(unique=True, verbose_name='Тип дополнительной услуги'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='description',
            field=models.TextField(verbose_name='Описание тренировки'),
        ),
    ]
