import 'package:flutter/material.dart';
import 'package:auto_route/auto_route.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:mobile_trampoline_park/application/application_part.dart';
import 'package:mobile_trampoline_park/domain/domain_part.dart';
import 'package:mobile_trampoline_park/presentation/enums/status_enum.dart';
import 'package:mobile_trampoline_park/presentation/extensions/extensions_part.dart';
import 'package:mobile_trampoline_park/presentation/resources/constants/constants_part.dart';
import 'package:mobile_trampoline_park/presentation/resources/theme_resources.dart/theme_resources_part.dart';
import 'package:mobile_trampoline_park/presentation/routing/app_routing.gr.dart';
import 'package:mobile_trampoline_park/presentation/widgets/widgets_part.dart';
import 'package:video_player/video_player.dart';
import 'package:yandex_mapkit/yandex_mapkit.dart' as mapkit;

part 'client_home_part.freezed.dart';
part 'client_home_screen.dart';
part 'video_player_widget.dart';
part 'yandex_map_widget.dart';
part 'bloc/client_home_bloc.dart';
part 'bloc/client_home_state.dart';
part 'bloc/client_home_event.dart';
part 'header_section_widget.dart';
