services:
    static:
        build:
            context: .
        restart: unless-stopped
        networks:
            - web
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=web'
            - 'traefik.http.routers.static.rule=Host(`trampolinepark1.ru`) && (PathPrefix(`/.well-known`) || PathPrefix(`/public`) || PathPrefix(`/media`))'
            - 'traefik.http.services.static.loadbalancer.server.port=80'
        volumes:
            - media:/usr/share/nginx/html/media
volumes:
    media:
networks:
    web:
        external: true
