services:
    static:
        build:
            context: .
        restart: unless-stopped
        networks:
            - web
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=web'
            - 'traefik.http.routers.static.rule=Host(`trampolinepark.localhost`) && (PathPrefix(`/.well-known`) || PathPrefix(`/public`))'
            - 'traefik.http.services.static.loadbalancer.server.port=80'
networks:
    web:
        external: true
